### ISSUE TITLE
Would u mind to add support for TW region?

### ISSUE THREAD

**Issue by zzz6839** [Antosik/lol-rss#50]
As title suggested, really appreciate if you could do that :)

**Comment by Antosik** [comment]
Hi!
Thanks for the feedback!

lol-rss is a bit outdated and was superseded by rito-news (my another project for LoL/VALORANT/etc. news)
Please migrate to it 🙏 

In rito-news you can use
- a web app (https://rito-news.pages.dev/?locale=zh-tw)
- a [raw JSON data](https://rito-news.iamantosik.me/lol/zh-tw/news.json), [RSS](https://rito-news.iamantosik.me/lol/zh-tw/news.rss), [Atom](https://rito-news.iamantosik.me/lol/zh-tw/news.atom) or even [JSONFeed](https://rito-news.iamantosik.me/lol/zh-tw/news.jsonfeed) ([guide](https://github.com/Antosik/rito-news-feeds/tree/main/docs/en))
- a [Golang package](https://github.com/Antosik/rito-news) (if you familiar with it)

**Comment by zzz6839** [comment]
thanks for your contribution!
